### ISSUE TITLE
Crash when placing speakers

### ISSUE THREAD

**Issue by Badcholo** [PC-Logix/OpenFM#1]
Crashed when placing a speaker.
http://pastebin.com/rEFZfnn3

I managed to add in a URL of a streaming radio station.
http://livestre.am/Sy0D

It reject it so i esc out of the window and i placed a speaker.
Crashh

good luck

**Comment by CaitlynMainer** [comment]
Well, on your second point, livestre.am isn't a service that is supported, to find stations that can be used with this mod check sites like http://www.shoutcast.com/  download the m3u playlist, open it in notepad or the like and grab the stream URL from it.

I'll try to resolve the crash with speakers if you don't have OpenComputers installed in a bit.

**Comment by CaitlynMainer** [comment]
Grab build 4 as soon as it's up on Curse and let me know if that fixes the crash.

**Comment by Badcholo** [comment]
thanks

**Comment by Badcholo** [comment]
Yeah, i guess it seems kinda hard to find a stream that is supported, I have never listened to any, so i don't even know what it is. 
, so the speaker does not cause me to crash anymore when placed and i was even able to link it.
I can't find a url that works, i have went to shoutcast and downloaded the file in 3 different ways.
I opened it with notepad++ and have got many different links and it says none are a supported format. ??

**Comment by CaitlynMainer** [comment]
I've been listening to http://72.13.86.4:8529 Which is dubstep, http://listen.radionomy.com/DeepHouse  Which is house music, http://69.4.232.118:80/live Which was Metal IIRC
