### ISSUE TITLE
Feature Suggestion: Saved Stations.

### ISSUE THREAD

**Issue by Badcholo** [PC-Logix/OpenFM#10]
Ability to save X amount of radio stations.
Wrench ability so the block retains saved information.

**Comment by CaitlynMainer** [comment]
Wrenching was a pain to implement without using APIs from tons of mods.  Radios retain NBT when broken, to clear a radio place it in a crafting table, and it'll give you a fresh radio

**Comment by Badcholo** [comment]
I like it.
