### ISSUE TITLE
Crashing while clicking radio block on server

### ISSUE THREAD

**Issue by excelcrafter** [PC-Logix/OpenFM#11]
It works in singleplayer, even with forge 1500+

but it crashes, when I have this mod on server

server forge: 1492
modpack: http://technicpack.net/modpack/proton-colony
latest java

edited---

mod version: OpenFM-0.1.0-7.jar

crash: http://pastebin.com/Kr4rwYYb

**Comment by CaitlynMainer** [comment]
Did you have a previous build of the mod installed  and updated to latest?

**Comment by excelcrafter** [comment]
I am sorry, I forget to send mod version, here it is:

OpenFM-0.1.0-7.jar

**Comment by CaitlynMainer** [comment]
I knew you had Build 7, otherwise you'd not have that line ,was this an update from a previous build, or a fresh install?

**Comment by excelcrafter** [comment]
It was fresh install, never used that mod before, but I found it acciddentally and instantly did fall in love with it :D

**Comment by CaitlynMainer** [comment]
Fixed build will be on Curse as soon as they approve it.

**Comment by CaitlynMainer** [comment]
Which is now.

**Comment by excelcrafter** [comment]
that was hell fast :D
