### ISSUE TITLE
[Request] Make it portable.

### ISSUE THREAD

**Issue by Shuudoushi** [PC-Logix/OpenFM#16]
Make a portable version of the radio and limit the hell out of it somehow. As always, helpful af :P

**Comment by CaitlynMainer** [comment]
As far as I can tell, the player requires a location, and without restarting the stream that location can't change.

**Comment by Badcholo** [comment]
There is a mod called mp3something, i'll look for it. What it did was play mp3 files from a specific folder.
i'm not asking you to make this, but would it be hard to make a mp3 player item that when right clicked would search that folder, show the files in a GUI and make them playable?
It would pretty much be a mp3 player integrated into minecraft, but would would be pretty sweet to not have to exit minecraft to change or play your music. I understand that others won't be able to hear your music and that when they hold the item. it would show what is in their folder, if anything at all. I have seen a mod make this, but it only added 3 keyboard buttons to press for play, stop, next song. It was very hard to use as well and got no updates. 
This is more of a comment, i'm just looking for advice on how difficult it would be to make this.
I might give it a try if i can't find anyone interested.
