### ISSUE TITLE
Crashing client when breaking down a tree with TCon tools

### ISSUE THREAD

**Issue by shortybsd** [PC-Logix/OpenFM#18]
When knocking down a tree with Tinker's Construct tools it crashes the client with this error - http://pastebin.com/svcvTw3c

I haven't looked at your source due to time, but does your mod trigger on every single block "break" event or just blocks from your mod? I was just curious why your mod is checking trees/wood blocks.

**Comment by CaitlynMainer** [comment]
There is no way to subscribe to just blockbreaks on a specific mod.  This has also already been fixed. fb7410276e7a71a55dd6e39b6910db7e41b49b47
