### ISSUE TITLE
Server disconnect when certian URL's are placed into a radio and play is hit

### ISSUE THREAD

**Issue by PotatoTrumpet** [PC-Logix/OpenFM#19]
When using certain URL's in a radio then hitting play while on a server, you will be disconnected with the error "A fatal error has occured, this connection is terminated" yet MC won't crash.

Reproduction:
Paste this link in radio and hit play
http://192.81.248.192:8080/

Also, talk to Me (Antheus) or Lizzy on IRC

**Comment by LizzyTrickster** [comment]
Stream link was from http://realpunkradio.com/ and extracted from the iTunes *listen on your favourite player* .pls file

**Comment by PotatoTrumpet** [comment]
let it also be noted that any players with in a unknown radius to it will also crash. Only know way to fix it is to World Edit the radio out

**Comment by CaitlynMainer** [comment]
Fixed in bb82797

**Comment by Alaberti** [comment]
Because it's related, I'd like to toss my two cents in - on version 17, I had a player press play with the default streamURL entry left unchanged and they got this error.

**Comment by CaitlynMainer** [comment]
I need logs @Alaberti This should be fixed in 17.

**Comment by Alaberti** [comment]
http://pastebin.com/kYCA9zGp

This was in 17. It was a pain to trace down because it's buried in the fml logs.
