### ISSUE TITLE
Radio doesn't resume on login.

### ISSUE THREAD

**Issue by CaitlynMainer** [PC-Logix/OpenFM#2]
This is because I have to do 2 packets on my getDescriptionPacket... really need to work around that.

**Comment by Badcholo** [comment]
Yeah, It has to be broken and placed again to work.
This would be amazing for a server spawn.
If you can get it to keep playing after a server restarts and/or chunks unload.
It would be awesome to hear music every time i had to into spawn.
Specially on my first day.
Any way of using dropbox to upload music like Better Records mod?
They have something similar, 
Let me know when it's Ready for a mod showcase.
https://www.youtube.com/watch?v=5k0YWvtUvBY

**Comment by CaitlynMainer** [comment]
This is sorta fixed in build 4, it just doesn't sync the screen color on login right now.  Also no, in theory the streaming stuff I'm using allows you to link to a MP3, but it currently glitches badly.

**Comment by CaitlynMainer** [comment]
Build 6 should fix both the issue with resuming on logjn, and syncing color.

**Comment by Badcholo** [comment]
Can you post a link to your curse page on your main github page.
It will make it easier for players to download your mod or get back to it after checking out github.
I should bookmark it, but then i'd have to go thru so many.

**Comment by CaitlynMainer** [comment]
Huh, I thought I had done that... will do.

**Comment by Badcholo** [comment]
I'm testing this on my test server right now.
If this works i gotta figure out how make my actual server computer stream the Server Spawn music.

**Comment by Badcholo** [comment]
Confirmed, Music continues to play, even if the server restarts, player log on or off and even if the chuncks are unloaded.
I first time i placed this it did not work, but every time after it continues to play beyond anything happening to it. This mod is definetly going into Mojangsters Modpack and on my Server.
I'll have a Mod Showcase Today. I just gotta find some good stations and finish testing.
