### ISSUE TITLE
Blank url then player clicked play on version 0.1.0-17

### ISSUE THREAD

**Issue by shortybsd** [PC-Logix/OpenFM#21]
Had a player place a radio down then quickly press play. It disconnects him from the server with "A fatal error has occurred, this connection is terminated." Also anyone going near his area instantly get kicked with same error. Only thing that showed up on the server is this:
http://pastebin.com/DrjjE8zi

**Comment by CaitlynMainer** [comment]
The player is client only so a server log won't have much data.  The client (the first time it's tried not on reconnects) has debug info that I'd need.  Since it's not a "crash" it's just in the regular client logs.

**Comment by CaitlynMainer** [comment]
I was able to replicate this again... I'm working on a fix.

**Comment by shortybsd** [comment]
You are awesome :) and thank you very much!

**Comment by CaitlynMainer** [comment]
This is in build 18
