### ISSUE TITLE
Random radioblocks getting offline

### ISSUE THREAD

**Issue by excelcrafter** [PC-Logix/OpenFM#22]
Got 3 radioblocks streaming music on server. Server is restarted once a day. Atleast one-two of these radioblocks will get turned off in 24 hours, no idea why, then need to turn them on manually again.

Forge 1492

Custom modpack: http://www.technicpack.net/modpack/proton-colony.629460

Server IP: proton-colony.com:25565

webpage: http://protoncolonygen2.enjin.com

**Comment by CaitlynMainer** [comment]
Unless there is an error logged in the client log, this was most likely because the stream was interrupted for any number of reasons and the radio stopped trying to reconnect.

**Comment by excelcrafter** [comment]
thank you, there is no crash-log or anything similar, mod runs very smooth and it does exactly whats on the tin, it definetly deserves more downloads then it has.

**Comment by CaitlynMainer** [comment]
Thanks for the kind words. :D  I'll see if I can make the errors a bit more verbose so you'll know why the radio has stopped playing soon (tm).
