### ISSUE TITLE
Client crash on teleporting to another dimension

### ISSUE THREAD

**Issue by Fingercomp** [PC-Logix/OpenFM#23]
If I try to TP to another dimension (the Nether, the End etc.) using console commands in radio's range, client crashes, but not every time.
**OpenFM version**: 0.1.0.20
**Forge**: 10.13.4.1448 (Client)
**Server**: KCauldron-1.7.10-1492.152
**Crash log**: https://gist.github.com/Fingercomp/3c04e8fa137e37573757

**Comment by CaitlynMainer** [comment]
What is the URL the radio is streaming?

**Comment by Badcholo** [comment]
I always use the same forge version for client and server. I have had very odd things happen due to this.

**Comment by CaitlynMainer** [comment]
I've been teleporting between the nether/end/overworld for the last 10 minutes and have yet to experience a crash in my dev environment.

**Comment by Badcholo** [comment]
What are you using to Tp? Essentials? other? MultiWorld? Multiverse? plugin? mod?

**Comment by Badcholo** [comment]
I meant he's using cauldron and it might be some plugin that is just goofing up. 
:-)

**Comment by Fingercomp** [comment]
CoFH tpx, MultiWorld /goto, Essentials /warp, Vanilla /tp. Also crashed in single-player world.
URLs: http://listen.radionomy.com/DeepHouse, http://streaming.radionomy.com/Dance90 etc

**Comment by CaitlynMainer** [comment]
I still can't reproduce this, nor can I understand HOW that code is being called, those are MP3 streams, going through the MP3 decoder, somehow calling the OGG .stop() method and hitting MP3's stop event.

**Comment by CaitlynMainer** [comment]
Please try build 22 as soon as it's approved on curse.

**Comment by CaitlynMainer** [comment]
Any change @Fingercomp ?

**Comment by Fingercomp** [comment]
Client doesn't crash now, thanks.

**Comment by CaitlynMainer** [comment]
So strange... still trying to figure out how you got into the OGG player from the MP3 player... o_O  Glad it's fixed

**Comment by Fingercomp** [comment]
After server reboot, client crashes every time on TP. =\
**Crash**: http://puu.sh/lpkEx/48d4c987e0.png
**OpenFM**: 0.1.0.22

**Comment by CaitlynMainer** [comment]
I can't reproduce this on plain forge.  My only guess is Cauldron is doing something funky.

**Comment by Badcholo** [comment]
Start removing mods and see which one has the compatibility issue.
Also does it crash when you remove OpenFM?
Remove OpenFM first and see if your still getting the crash.

**Comment by Badcholo** [comment]
Make sure the configs are the same from the server to the client, also remove client fixer while doing this
