### ISSUE TITLE
[Feature Request] CD Drive for Music Discs

### ISSUE THREAD

**Issue by MyNameIsKodos** [PC-Logix/OpenFM#24]
It would be nice if there was a block that you could stick a music disc in (Vanilla or CMD) and call play() and stop()

Not sure how difficult it would be to implement.

**Comment by scj643** [comment]
A disc that has a stream or a list of streams would be nice.

**Comment by excelcrafter** [comment]
Jukebox :D 

PlayRandomStream()

with OpenComputers :D

**Comment by CaitlynMainer** [comment]
Memory cards for bookmarks or something maybe. Actual music disks, or support for them? No.

**Comment by CaitlynMainer** [comment]
Added Memory Cards in build 25
