### ISSUE TITLE
Sound is Very low.

### ISSUE THREAD

**Issue by Badcholo** [PC-Logix/OpenFM#3]
I can hear it now, but it is very low. i have added 6 speakers total but it seems to not be getting louder.
i'll keep adding more. i have turned on all my sound settings to high.

**Comment by Badcholo** [comment]
duh, never mind, i thought the + sign was to add another station. 
pressing on the plus increases the volume.

**Comment by CaitlynMainer** [comment]
I plan on working on the GUI soon (tm) to make stuff a bit clearer.  Also adding speakers doesn't make the sound any louder, it just allows you to increase the range.

**Comment by CaitlynMainer** [comment]
Added tooltips to all of the GUI buttons
