### ISSUE TITLE
openfm_radio.start() crashes client/server

### ISSUE THREAD

**Issue by IgorTimofeev** [PC-Logix/OpenFM#36]
Sometimes (i can't reproduce this, seems like random) server/client crashes when .start() Lua method is called. After crash and reloading client i can see this error on monitor:

![2016-03-19_02 44 36](https://cloud.githubusercontent.com/assets/11760002/13894773/2c505c68-ed85-11e5-89d0-499fc54334c2.png)

Here is Lua code part:

![2016-03-19 2 51 44](https://cloud.githubusercontent.com/assets/11760002/13894854/effbb4f0-ed85-11e5-9ae2-0051ecb9bffc.png)

Here is client console log:
[latest.txt](https://github.com/PC-Logix/OpenFM/files/180550/latest.txt)

And here is client crash report:
[crash-2016-03-19_02.32.56-server.txt](https://github.com/PC-Logix/OpenFM/files/180547/crash-2016-03-19_02.32.56-server.txt)

OpenFM version:
OpenFM-1.7.10-0.1.0-31.jar

OpenComputers version:
OpenComputers-MC1.7.10-1.5.21.41-universal.jar

**Comment by CaitlynMainer** [comment]
Please try build 32 as soon as it's approved on Curse.  Thanks

**Comment by IgorTimofeev** [comment]
@CaitlynMainer Crash again. But now without crash logs. Here is what i've done:

First, I inserted a non-playable URL using setURL(), it has immediately shown on radio screen. Then I tried to play it - nothing happend, and radio screen become empty:

![2016-03-19 7 41 34](https://cloud.githubusercontent.com/assets/11760002/13896678/b5f36aa4-edae-11e5-9c98-a712f78d8d52.png)

![2016-03-19 7 39 49](https://cloud.githubusercontent.com/assets/11760002/13896688/0e29b5b6-edaf-11e5-82eb-f7017eccfd70.png)

Second, I inserted a valid URL that usually plays normally on OpenFM. When I tried to start(), nothing happened, but radio screen displays an URL:

![2016-03-19 7 42 12](https://cloud.githubusercontent.com/assets/11760002/13896694/3bcbd2c4-edaf-11e5-8daf-cb94c3ab8406.png)

![2016-03-19 7 42 15](https://cloud.githubusercontent.com/assets/11760002/13896697/50573f12-edaf-11e5-8747-771238ba4d4e.png)

Third, i've just hit "Play" button on the GUI. Ta-dah! Client crash!

![2016-03-19 7 42 19](https://cloud.githubusercontent.com/assets/11760002/13896701/7f18124a-edaf-11e5-9853-a8e839560f04.png)

And there is no crash reports, no logs or something else, singleplayer just shutted down:

![2016-03-19 7 42 28](https://cloud.githubusercontent.com/assets/11760002/13896703/8d8d533a-edaf-11e5-94cd-db4b9c85b826.png)

**Comment by CaitlynMainer** [comment]
please try build 33

**Comment by IgorTimofeev** [comment]
@CaitlynMainer Everything works! Thanks for quick fixing :)
