### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by excelcrafter** [PC-Logix/OpenFM#37]
http://pastebin.com/fRg3bwXd

putting lever on a radio, switching redstone mode and lever will do the crash

**Comment by CaitlynMainer** [comment]
What dimension is the radio in? Overworld/Nether/End or some mod provided dim?

**Comment by excelcrafter** [comment]
the radio is in overworld

**Comment by CaitlynMainer** [comment]
Yeah, I found the issue, it's fixed in the latest build on curse

**Comment by excelcrafter** [comment]
I am trying to have radio "chunkloaded" with admin anchor from Railcraft, when I leave the chunk and teleport somewhere and back radio stops playing.
