### ISSUE TITLE
Crash with creative tab

### ISSUE THREAD

**Issue by Badcholo** [PC-Logix/OpenFM#4]
So i created the test server. I went into creative. When i go into the page that has the mods tab in it.
I get a crash. I have copied the servers generated config to the client and still causes a crash.

Client crash
http://pastebin.com/u1fht8sr

I can give you the server logs, but i don't think that will help much.
The server keeps running just fine.

**Comment by CaitlynMainer** [comment]
I can't reproduce this locally http://michi.pc-logix.com/Minecraft_1.7.10_2015-10-10_12-51-00.png  No crashing here.. also that is the most useless carsh report ever (Not your fault), thanks Forge.

**Comment by Badcholo** [comment]
I'll get clean client logs

**Comment by Badcholo** [comment]
https://www.dropbox.com/sh/zaoe7lbightlhk2/AACC6JGdmUkBrEU7y7DGBgsya?dl=1

**Comment by CaitlynMainer** [comment]
Yeah that doesn't say which item failed to render -_- You'd think that'd be an important thing to log.  Though I notice you're running kcauldron, a while back this was a known issue with cauldron sending bad data to the client for some TEs.  If I make a special build for you would you test it and let me know if it stops the crash?

**Comment by Badcholo** [comment]
Of Course

**Comment by CaitlynMainer** [comment]
http://michi.pc-logix.com/OpenFM-0.1.0-0.jar  This disables the fancy render overlay, which is the only thing I think would be possible to fail to render.

**Comment by Badcholo** [comment]
got it, i'll try it right now

**Comment by Badcholo** [comment]
I added the file to the Server and Client. Still crashes

**Comment by Badcholo** [comment]
I'll remove your mod to see if it can be anything else i might have done.

**Comment by CaitlynMainer** [comment]
Try removing the mod completely and seeing if you still crash, that code I removed is the only special rendering in the mod.

**Comment by Badcholo** [comment]
The last tab only had like 2 mods and it was just unlucky the one was yours.
I completely removed your mod and it still crashes, sry for all the trouble. 
It is not your mod.

**Comment by CaitlynMainer** [comment]
Whew, I was racking my brain trying to figure out what could be null rendering in a GUI Screen.

**Comment by Badcholo** [comment]
Sry, your mod is amazing by the way.
It was a mod that i had removed from the server, but forgot to remove it from the modpack.
I'm such an idiot. At least i fixed another issue with my modpack. Still can't find anything wrong with your mod. You've done such a great job!!
