### ISSUE TITLE
Crash trying to play the radio

### ISSUE THREAD

**Issue by vpontin** [PC-Logix/OpenFM#40]
Hi! I'm crashing when i paste this stream url and press play:

https://gist.github.com/vpontin/0bbd016875fbc978c9b30f166eccc453

I'm using OpenFM-1.9.4-0.1.0.4, Minecraft 1.10.2 (i assume most 1.9.4 mods are compatible with 1.10.x) and Forge b2014.
The stream url is: http://198.154.106.109:7998/ and according with Winamp:
```
Server: SHOUTcast Distributed Network Audio Server/Linux v1.9.8
Content-Type: audio/mpeg
```

**Comment by CaitlynMainer** [comment]
No, in this case OpenFM isn't 1.10 compatible, there were some minor changes in the networking system that I've got to port for

**Comment by vpontin** [comment]
Uh i understand.

I hate asking ETAs, but now with gamax92 helping in the network system, do you have plans to port to 1.10?

Thanks in advance!

**Comment by CaitlynMainer** [comment]
Actually I can't reproduce that running OpenFM-1.9.4-0.1.0.4.jar with Forge 1.10.2-12.18.1.2014.  Though the coremod doesn't run so the SPIs that do the decoding don't get extracted so nothing plays.

**Comment by CaitlynMainer** [comment]
Any updates on this...?

**Comment by vpontin** [comment]
Oh i'm sorry, i will try to test using another stream.

**Comment by vpontin** [comment]
Running the latest version (OpenFM-1.9.4-0.1.0.5) on a fresh (no mods) Forge profile with the same build (1.10.2 b2014) dont gives any errors. I will test on my "Production" build before closing
