### ISSUE TITLE
Crash when renaming the radio Screen Text

### ISSUE THREAD

**Issue by vpontin** [PC-Logix/OpenFM#41]
I think this is unrelated to #40 , so why i create another issue for that.

While testing things related to the prior issue, i tried, randomly, to rename the screen text and the game crashed with the following log:
https://gist.github.com/vpontin/7edca5eba35975733fb19eac0b295349

Trying to reload the world after this also crash the game with the same log, rendering the world unplayable.

Using:
- Minecraft 1.10.2
- Forge 1.10.2 b2014
- OpenFM 1.9.4 0.1.0.5

**Comment by vpontin** [comment]
Thanks, doesnt crash anymore! But the screen text doesnt show up anymore.

_Before_
![2016-07-18_02 19 58](https://cloud.githubusercontent.com/assets/3485505/16906445/4d2d6184-4c8e-11e6-91a3-b3cec21615b6.png)

_Now_
![2016-07-18_02 23 48](https://cloud.githubusercontent.com/assets/3485505/16906477/e4651e0c-4c8e-11e6-96b7-49c53df60c8f.png)

Is this intended?

**Comment by CaitlynMainer** [comment]
Pretty much, yes.  In 1.9+ the TESR changed and became VERY annoying to use and made the way I render text almost not work. Rendering the default text works, but rendering other text gets... interesting.

**Comment by vpontin** [comment]
Okay. Thanks!

**Comment by CaitlynMainer** [comment]
the latest build I ran ( a few hours ago) will at least show the first 6 characters of any title you set.

**Comment by vpontin** [comment]
Yeah! Thanks for the fix!

**Comment by CaitlynMainer** [comment]
And a build I pushed a few days ago fixes scrolling in 1.9+
