### ISSUE TITLE
Breaking a radio drops no item

### ISSUE THREAD

**Issue by RyanP1991** [PC-Logix/OpenFM#42]
Breaking the radio drops no item

**Comment by CaitlynMainer** [comment]
What MC version? What OpenFM build?  Are you in survival or creative?  Did you break it with your hand or a tool?

**Comment by RyanP1991** [comment]
Sorry for the crappy bug report had to run out quickly. So here is the proper one.

MC Version - 1.10.2 
Forge version - 12.18.1.2014
Mod Version - 0.1.0.7 the only version for 1.10.2
I was in survival and used a iron pickaxe / iron axe and tinker tools all of them drop no item.

**Comment by CaitlynMainer** [comment]
All of the 1.9.4 builds work on 1.10, I only tagged the latest cause it's the only one I tested to start.  I'll look into this when I get home (I'm at work), I know they dropped items in 1.9 I'm wondering if something minor changed.  Thanks for the report.
