### ISSUE TITLE
Crash when Launching on Server

### ISSUE THREAD

**Issue by kosakriszi** [PC-Logix/OpenFM#47]
MC: 1.10.2
OpenFM: latest build (at time of posting)

Seems to be trying to loading the GUI class on the server:
http://pastebin.com/dTx4tQfk

**Comment by CaitlynMainer** [comment]
I can't reproduce this: http://michi.pc-logix.com/javaw_2016-07-28_07-12-39.png

**Comment by CaitlynMainer** [comment]
` at java.lang.Class.getDeclaredFields(Class.java:1916)
    at org.spongepowered.common.registry.provider.BlockPropertyIdProvider.getIdAndTryRegistration(BlockPropertyIdProvider.java:92)
    at org.spongepowered.common.registry.type.BlockTypeRegistryModule.registerBlockTrait(BlockTypeRegistryModule.java:128`


This is sponges doing... I have no idea how it's getting to my GUI class from my block but hey.

**Comment by CaitlynMainer** [comment]
Please test this as soon as curse approves it: http://minecraft.curseforge.com/projects/openfm/files/2319281

**Comment by MastaC729** [comment]
Awesome, this newest build works just fine with Sponge. Thanks for the quick response. This is my first time using your mod, so I can't wait to play around with it. :)
