### ISSUE TITLE
can't control it in ComputerCraft 

### ISSUE THREAD

**Issue by veso266** [PC-Logix/OpenFM#48]
Hi I've installed the latest verson for MC 1.7.10 and I have ComputerCraft installed and java 8

but when I do:
`peripheral.wrap("left")`
`fm.setURL("http://listen.radionomy.com/DeepHouse")`
`fm.start()`

I get `lua:1 java.lang.String cannot be cast to [B`

(i got the error before I even do fm.start()

Thanks for Help and Best Regards

**Comment by PixelFox1** [comment]
Bump

**Comment by CaitlynMainer** [comment]
This issue should have been resolved quiet a while ago, please reopen / comment if not.
