### ISSUE TITLE
vorbisspi-1.0.3-1.jar location

### ISSUE THREAD

**Issue by Scratchman** [PC-Logix/OpenFM#49]
\o

Up until the last update for 1.7.10 this file has always been downloaded to /mods/1.7.10, but after the last update the file is now being downloaded to /mods, but it's not deleting the .jar that is in the /mods/1.7.10 folder.

Is the new download location intentional?

I'm going to hold off on updating the mod this month because I'm almost finished the completing the update to the server.

Thanks for the wonderful work you do on this mod Mich. :)

ETA: also, just found that mp3spi-1.9.5-1.jar is doing the same thing.

**Comment by CaitlynMainer** [comment]
Yes, this was intended, either one can be present, both can be present, it doesn't matter.
