### ISSUE TITLE
Speakers lose connection upon Restart

### ISSUE THREAD

**Issue by Badcholo** [PC-Logix/OpenFM#5]
I believe the speakers lost connection to the FMPlayer upon restart, but i'm unsure.
It may have been upon chunck loading or logging off, i'll look into it.

**Comment by CaitlynMainer** [comment]
I also can't reproduce this locally, I have speakers in my test area, and they seem to work across restarts, and chunk loads/unloads.

**Comment by Badcholo** [comment]
This was my fault. I had to break the FMplayer the first time and then after it workes great.
Everything is running smooth. Sry.
