### ISSUE TITLE
OpenFM 1.9.4 works just fine on 1.10.2

### ISSUE THREAD

**Issue by C0rn3j** [PC-Logix/OpenFM#50]
OpenFM-1.9.4-0.1.0.14.jar

Why is it not marked as supporting both 1.9.4 and 1.10.2? The last few versions worked just fine with it!

**Comment by CaitlynMainer** [comment]
They have been marked as supporting 1.10 on curse it's just not in the file name, as the code base is 1.9, NOT 1.10
