### ISSUE TITLE
Client crash: "Unexpected Error"

### ISSUE THREAD

**Issue by gdude2002** [PC-Logix/OpenFM#54]
Oh boy, I'm just finding all the crashes lately, aren't I. xD

MC: 1.10.2
Forge: 12.18.3.2185
OFM: 0.1.0.18
Stream URL: `http://radio.vgmradio.com:8040/stream`

[crash-2016-12-22_09.54.32-client.txt](https://github.com/PC-Logix/OpenFM/files/668475/crash-2016-12-22_09.54.32-client.txt)

Completely random crash this time. I was AFK, came back to my machine, moved around a little and let it idle with the chat input open. A few minutes later, it crashed on its own.

**Comment by CaitlynMainer** [comment]
Hopefully fixed in Build 21
