### ISSUE TITLE
Feature Suggestion:

### ISSUE THREAD

**Issue by Badcholo** [PC-Logix/OpenFM#6]
I wanted to leave your FMPlayer at spawn with a Stage I built, but even thou spawn is protected players can still get into your player and change the settings. Maybe a creative item to lock it from others?
![2015-10-10_12 24 00](https://cloud.githubusercontent.com/assets/10932905/10412928/4f3f88b0-6f4b-11e5-8170-e11d42c795c9.png)

**Comment by CaitlynMainer** [comment]
There is a new button on the GUI that lets you lock the radio to allow only the owner to open the GUI or break the block.  (Exceptions for Ops, they're able to open the GUI, and can then unlock it to break it)

**Comment by Badcholo** [comment]
Very Nice!
