### ISSUE TITLE
ETA for 1.11.x

### ISSUE THREAD

**Issue by vpontin** [PC-Logix/OpenFM#60]
I know this kind of topic is very rude, but out of curiosity, do you have plans for update OpenFM? If yes, is there any ETA??

Thanks in advance

**Comment by vpontin** [comment]
Yeah, i was very inappropriate in this thread, sorry.

And thanks a lot for keeping the mod updated to 1.12.2!

**Comment by CaitlynMainer** [comment]
It's not that it was inappropriate, I just never ported it to 1.11, and moved directly to 1.12.

**Comment by vpontin** [comment]
Oh yeah, i didnt pay attention for this detail
