### ISSUE TITLE
Don't launching with OpenFM

### ISSUE THREAD

**Issue by DromHour** [PC-Logix/OpenFM#62]
Whild have this mod, Minecraft do not launching at all. No crash-reports. No errors. No logs.

**Comment by MajorGeneralRelativity** [comment]
If you remove the mod and make no other changes, does Minecraft launch?

**Comment by CaitlynMainer** [comment]
I'm not sure where to even start here..
Minecraft version, Forge version, OpenFM version, Java version, OS version... matter of fact if it has a version number, I'd like to see it.

**Comment by DromHour** [comment]
Minecraft 1.7.10
Forge 
OpenFM latest for 1.7.10
Java 8u131-win64
Windows 10 Creators update
MCP 9.05 
FML 7.10.99.99 
Minecraft Forge 10.13.4.1614


It launching without OpenFM.
modlist:
	UCHIJA	mcp{9.05}
	UCHIJA	FML{7.10.99.99}
	UCHIJA	Forge{10.13.4.1614}
	UCHIJA	appliedenergistics2-core{rv3-beta-6}
	UCHIJA	CodeChickenCore{1.0.7.47}
	UCHIJA	ivtoolkit{1.2.1}
	UCHIJA	NotEnoughItems{1.0.5.118}
	UCHIJA	OpenComputers|Core{1.6.2.12}
	UCHIJA	RenderPlayerAPI{1.3}
	UCHIJA	OpenModsCore{0.10}
	UCHIJA	appliedenergistics2{rv3-beta-6}
	UCHIJA	BiblioCraft{1.11.5}
	UCHIJA	clearingblock{0.3}
	UCHIJA	colorblocksplus{1.0}
	UCHIJA	davincing{1710.1.8}
	UCHIJA	grim3212core{V0.2 - 1.7.10}
	UCHIJA	doubledoors{V0.1 - 1.7.10}
	UCHIJA	IronChest{6.0.62.742}
	UCHIJA	JABBA{1.2.2}
	UCHIJA	MoarSigns{1.2.4}
	UCHIJA	Monoblocks{1.10.39} 
	UCHIJA	MonoblocksMultipart{1.10.39}
	UCHIJA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod]
	UCHIJA	MrTJPCoreMod{1.1.0.33}
	UCHIJA	OpenMods{0.10}
	UCHIJA	OpenBlocks{1.6}
	UCHIJA	OpenComputers{1.6.2.12}
	UCHIJA	plantmegapack{4.02}
	UCHIJA	ResourceLoader{1.3}
	UCHIJA	CustomMainMenu{1.9.2}
	UCHIJA	wallcraftmod{1.0}
	UCHIJA	Ztones{1.7.10}
	UCHIJA	betterstorage{0.13.1.126}
	UCHIJA	endercore{1.7.10-0.2.0.39_beta}
           ^
            |
don't care about it, I copied that from logs

**Comment by MajorGeneralRelativity** [comment]
A. How much RAM do you have allocated to MC?
B. Try launching it with only OpenComputers and OpenFM

**Comment by DromHour** [comment]
thx, i'll try...
My players tried to use 3GB(usually 2GB is more than need), but it still not launching

**Comment by MajorGeneralRelativity** [comment]
Is this an issue you are personally experiencing, or is it someone on your server?

**Comment by CaitlynMainer** [comment]
Can you zip your mods and config folder and put it somewhere I can download?

**Comment by DromHour** [comment]
kk, now in pack will be some new(not listed) mods because I not created modpack completely. Mods in "noload" just to use it in future(My internet 2MiB/S....)
[https://yadi.sk/d/NiRVpLdJ3HxtBB](url)
I found logs(why before it not recorded???), but too late and uploaded it as second file: [https://yadi.sk/d/q_-hnFZj3HxtTM](url)

**Comment by MajorGeneralRelativity** [comment]
Both of those links show up as broken

**Comment by DromHour** [comment]
idk why(my megahands), but...
![image](https://cloud.githubusercontent.com/assets/26818130/25900845/0b9ca3b8-35bf-11e7-9c72-67bdf50710ef.png)
just copy-paste link

**Comment by CaitlynMainer** [comment]
They work if you copy/paste them, github's URL parser derped...

**Comment by MajorGeneralRelativity** [comment]
Ah, my bad

**Comment by CaitlynMainer** [comment]
Well... I don't have any of your custom resources, but the game loads fine for me with your mods and config dirs

**Comment by DromHour** [comment]
wtf... which java you using?

**Comment by CaitlynMainer** [comment]
My desktop is Java 8_111

**Comment by MajorGeneralRelativity** [comment]
Have you tried it without your custom resources?

**Comment by CaitlynMainer** [comment]
Your log seems to stall when OpenFM tries to extract the SPI jars... and ALL of your paths seem very... odd.  How are you launching MC?

**Comment by DromHour** [comment]
It sashok's launcher, very popular in Russia... With it, Imy project have custom authentication, skins and caps + hash checker(anticheat)
Idk more because I responsible only for mods and their configs... I can upload our launcher in PM(to not ad server)

**Comment by CaitlynMainer** [comment]
I'm not going to even TRY to support a pirated launcher, they do SO many stupid things to MC.

**Comment by MajorGeneralRelativity** [comment]
I'd like to also mention that pirated launchers are illegal, and you are breaking copyright laws by not paying for MC

**Comment by CaitlynMainer** [comment]
^ This too.
