### ISSUE TITLE
[1.12.2] ComputerCraft1.80pr1

### ISSUE THREAD

**Issue by hartontw** [PC-Logix/OpenFM#69]
Any attempt to wrap or find the radio as peripheral results in null or false.

I'm trying to guess what is happening looking at source...

Any position:
peripheral.wrap('left') -->nil
peripheral.find('openfm_radio') -->nil

**Comment by CaitlynMainer** [comment]
Right, when I released the ports for 1.10 and 1.12 these builds didn't exist so the CC API was removed and the CC specific code went unused.  Test http://ci.pc-logix.com/job/OpenFM-1.12/16/ the build here and let me know if it works for you please.

**Comment by CaitlynMainer** [comment]
Build 17 fixes ComputerCraft compat
