### ISSUE TITLE
Ridiculous request

### ISSUE THREAD

**Issue by vpontin** [PC-Logix/OpenFM#72]
I know this is a bit small, but can you make parrots dance when around a radio [just like they do when nearby a jukebox](https://minecraft.gamepedia.com/Parrot#Dancing)?

Thanks in advance!

**Comment by ben-mkiv** [comment]
sadly cant be done at the moment as minecraft checks if its a jukebox block.

leaving this as note for a forge PR
```
1. make the actual tag json
2. in Forge's Tags.Block class, add a field for the tag similar to all the other ones there
3. at the vanilla code site, replace the check with net.minecraftforge.<dontremember>.Tags.Block.PARTY_BLOCKS.contains(block)
``` thanks to williewillus :)

**Comment by vpontin** [comment]
Oh sad. Thanks for the reply anyway!
