### ISSUE TITLE
Reset Button - Reload the FMplayer

### ISSUE THREAD

**Issue by Badcholo** [PC-Logix/OpenFM#8]
On my test server i have left the music playing, but if i crash the server, due to worldedit or a mod that just crashes the server the music stops playing. 

I have installed this onto my main server and without crashing, all of a sudden the music does not play. I'm not sure what is causing it, but a Reset Button could be useful. possibly even redstone activated. I mean so that if it does crash or stop working, every 15min, the FMplayer would get reset to the station it was set to and would begin to play again. I'm having at the moment to break the block, input the station link and connect all the speakers to it again.

**Comment by CaitlynMainer** [comment]
When this happens could you check your client logs for an error from OpenFM about a bitstream error 102?  If you get that it means the stream was interrupted from the other end of the connection.  Also, redstone control is implemented, click the redstone dust icon next to the close button to toggle it then a redstone pulse will change the radios state.

**Comment by Badcholo** [comment]
will do..
Thanks. i'm at work, i get home in 5hrs.
The redstone pulse i mean would have to reset the radio station as if i had broke it and placed in a stream link again.
